<?php

/**
 * @copyright Copyright &copy; Gogodigital Srls
 * @company Gogodigital Srls - Wide ICT Solutions 
 * @website http://www.gogodigital.it
 * @github https://github.com/mahmuds/mastrack-articles
 * @license GNU GENERAL PUBLIC LICENSE VERSION 3
 * @package mastrack-articles
 * @version 0.6.3
 */

use mahmuds\articles\migrations\Migration;
use yii\db\Schema;

class m151021_200427_create_article_items_table extends Migration
{

    public function init()
    {
        $this->db = 'ecommercedb';
        parent::init();
    }

    public function up()
    {
        $this->createTable('{{%article_items}}', [
            'id' => $this->primaryKey(),
            'title' => $this->string(255)->notNull(),
            'alias' => $this->string(255)->notNull(),
            'catid' => $this->integer(11)->notNull()->defaultValue(0),
            'userid' => $this->integer(11)->notNull()->defaultValue(0),
            'introtext' => $this->text(),
            'fulltext' => $this->text(),
            'state' => $this->boolean()->notNull()->defaultValue(0),
            'access' => $this->string(64)->notNull(),
            'language' => $this->char(7)->notNull(),
            'theme' => $this->string(12)->notNull()->defaultValue('blog'),
            'ordering' => $this->integer(11)->notNull()->defaultValue(0),
            'hits' => $this->integer(11)->notNull()->defaultValue(0),
            'image' => $this->text(),
            'image_caption' => $this->string(255),
            'image_credits' => $this->string(255),
            'video' => $this->text(),
            'video_type' => $this->string(20)->defaultValue(null),
            'video_caption' => $this->string(255)->defaultValue(null),
            'video_credits' => $this->string(255)->defaultValue(null),
            'created' => $this->dateTime()->notNull(),
            'created_by' => $this->integer(11)->notNull()->defaultValue(0),
            'modified' => $this->dateTime()->notNull(),
            'modified_by' => $this->integer(11)->notNull()->defaultValue(0),
            'params' => $this->text(),
            'metadesc' => $this->text(),
            'metakey' => $this->text(),
            'robots' => $this->string(20)->defaultValue(null),
            'author' => $this->string(50)->defaultValue(null),
            'copyright' => $this->string(50)->defaultValue(null)
        ], $this->tableOptions);

        $now = new \yii\db\Expression('now()');

        $this->batchInsert('{{%article_items}}',
            ["id", "title", "alias", "catid", "userid", "introtext", "fulltext", "state", "access", "language", "theme", "ordering", "hits", "image", "image_caption", "image_credits", "video", "video_type", "video_caption", "video_credits", "created", "created_by", "modified", "modified_by", "params", "metadesc", "metakey", "robots", "author", "copyright"],
            [
                [
                    'id' => '1',
                    'title' => 'Yii2 AdminLTE',
                    'alias' => 'yii2-admin-lte',
                    'catid' => '1',
                    'userid' => '1',
                    'introtext' => '<p><strong>Yii2 AdminLTE</strong> è un semplice Asset Bundle realizzato per includere <strong>AdminLTE</strong>, un tema stile pannello di controllo basato su <strong>Twitter Bootstrap 3</strong></p>',
                    'fulltext' => '<p><strong>Yii2 AdminLTE</strong> è un semplice Asset Bundle realizzato per includere <strong>AdminLTE</strong>, un tema stile pannello di controllo basato su <strong>Twitter Bootstrap 3</strong></p>',
                    'state' => '1',
                    'access' => 'public',
                    'language' => 'all',
                    'theme' => 'blog',
                    'ordering' => '1',
                    'hits' => '0',
                    'image' => '',
                    'image_caption' => '',
                    'image_credits' => '',
                    'video' => '',
                    'video_type' => 'youtube',
                    'video_caption' => '',
                    'video_credits' => '',
                    'created' => '2016-04-05 12:17:44',
                    'created_by' => '9900',
                    'modified' => '2016-10-01 22:01:37',
                    'modified_by' => '9900',
                    'params' => '',
                    'metadesc' => '',
                    'metakey' => '',
                    'robots' => 'index, follow',
                    'author' => 'Gogodigital S.r.l.s.',
                    'copyright' => 'Gogodigital S.r.l.s.',
                ],[
                    'id' => '2',
                    'title' => 'Yii2 Articles',
                    'alias' => 'yii2-articles',
                    'catid' => '1',
                    'userid' => '1',
                    'introtext' => '<p><strong>Yii2 Articles</strong> è una estensione per creare, gestire e cancellare <strong>articoli</strong> su un sito Yii2, con categorie, allegati, multilingua, RBAC, ecc...</p>',
                    'fulltext' => '',
                    'state' => '1',
                    'access' => 'public',
                    'language' => 'all',
                    'theme' => 'blog',
                    'ordering' => '2',
                    'hits' => '0',
                    'image' => '',
                    'image_caption' => '',
                    'image_credits' => '',
                    'video' => '',
                    'video_type' => 'youtube',
                    'video_caption' => '',
                    'video_credits' => '',
                    'created' => '2016-04-23 03:31:32',
                    'created_by' => '9900',
                    'modified' => '2016-04-23 04:19:17',
                    'modified_by' => '9900',
                    'params' => '',
                    'metadesc' => '',
                    'metakey' => '',
                    'robots' => 'index, follow',
                    'author' => 'Gogodigital S.r.l.s.',
                    'copyright' => 'Gogodigital S.r.l.s.',
                ],[
                    'id' => '3',
                    'title' => 'Yii2 Cookie Consent',
                    'alias' => 'yii2-cookie-consent',
                    'catid' => '1',
                    'userid' => '1',
                    'introtext' => '<p><strong>Yii2 Cookie Consent</strong> è una estensione che permette di inserire all\'interno del proprio sito Yii 2 lo script <strong>Cookie Consent 2</strong> per l\'avviso sui Cookie degli utenti</p>',
                    'fulltext' => '',
                    'state' => '1',
                    'access' => 'public',
                    'language' => 'all',
                    'theme' => 'blog',
                    'ordering' => '3',
                    'hits' => '0',
                    'image' => '',
                    'image_caption' => '',
                    'image_credits' => '',
                    'video' => '',
                    'video_type' => 'youtube',
                    'video_caption' => '',
                    'video_credits' => '',
                    'created' => '2016-04-23 03:32:35',
                    'created_by' => '9900',
                    'modified' => '2016-04-23 03:49:58',
                    'modified_by' => '9900',
                    'params' => '',
                    'metadesc' => '',
                    'metakey' => '',
                    'robots' => 'index, follow',
                    'author' => 'Gogodigital S.r.l.s.',
                    'copyright' => 'Gogodigital S.r.l.s.',
                ],[
                    'id' => '4',
                    'title' => 'Yii2 Font Awesome',
                    'alias' => 'yii2-font-awesome',
                    'catid' => '1',
                    'userid' => '1',
                    'introtext' => '<p><strong>Yii2 Font Awesome</strong> è un semplice Asset Bundle realizzato per includere <strong>Font Awesome</strong> un toolkit con font ed icone basato su CSS e LESS.</p>',
                    'fulltext' => '',
                    'state' => '1',
                    'access' => 'public',
                    'language' => 'all',
                    'theme' => 'blog',
                    'ordering' => '4',
                    'hits' => '0',
                    'image' => '',
                    'image_caption' => '',
                    'image_credits' => '',
                    'video' => '',
                    'video_type' => 'youtube',
                    'video_caption' => '',
                    'video_credits' => '',
                    'created' => '2016-04-23 03:35:14',
                    'created_by' => '9900',
                    'modified' => '2016-04-23 03:58:25',
                    'modified_by' => '9900',
                    'params' => '',
                    'metadesc' => '',
                    'metakey' => '',
                    'robots' => 'index, follow',
                    'author' => 'Gogodigital S.r.l.s.',
                    'copyright' => 'Gogodigital S.r.l.s.',
                ],[
                    'id' => '5',
                    'title' => 'Yii2 Multilanguage',
                    'alias' => 'yii2-multilanguage',
                    'catid' => '1',
                    'userid' => '1',
                    'introtext' => '<p><strong>Yii2 Multi Language</strong> è una estensione che permette d\'inserire un <strong>supporto multilingua</strong> all\'interno di un sito Yii 2 con un widget di bandiere.</p>',
                    'fulltext' => '',
                    'state' => '1',
                    'access' => 'public',
                    'language' => 'all',
                    'theme' => 'blog',
                    'ordering' => '5',
                    'hits' => '0',
                    'image' => '',
                    'image_caption' => '',
                    'image_credits' => '',
                    'video' => '',
                    'video_type' => 'youtube',
                    'video_caption' => '',
                    'video_credits' => '',
                    'created' => '2016-04-23 03:42:28',
                    'created_by' => '9900',
                    'modified' => '2016-04-23 04:05:40',
                    'modified_by' => '9900',
                    'params' => '',
                    'metadesc' => '',
                    'metakey' => '',
                    'robots' => 'index, follow',
                    'author' => 'Gogodigital S.r.l.s.',
                    'copyright' => 'Gogodigital S.r.l.s.',
                ],[
                    'id' => '6',
                    'title' => 'Yii2 Paypal',
                    'alias' => 'yii2-paypal',
                    'catid' => '1',
                    'userid' => '1',
                    'introtext' => '<p><strong>Yii2 Paypal</strong> è un\'estensione Yii2 che permette di gestire i pagamenti <strong>Paypal</strong> sul tuo sito Yii2, con cronologia pagamenti e funzioni semplificate (In Sviluppo!)</p>',
                    'fulltext' => '',
                    'state' => '1',
                    'access' => 'public',
                    'language' => 'all',
                    'theme' => 'blog',
                    'ordering' => '6',
                    'hits' => '0',
                    'image' => '',
                    'image_caption' => '',
                    'image_credits' => '',
                    'video' => '',
                    'video_type' => 'youtube',
                    'video_caption' => '',
                    'video_credits' => '',
                    'created' => '2016-04-23 03:43:53',
                    'created_by' => '9900',
                    'modified' => '2016-04-23 04:09:19',
                    'modified_by' => '9900',
                    'params' => '',
                    'metadesc' => '',
                    'metakey' => '',
                    'robots' => 'index, follow',
                    'author' => 'Gogodigital S.r.l.s.',
                    'copyright' => 'Gogodigital S.r.l.s.',
                ],[
                    'id' => '7',
                    'title' => 'Yii2 User Extended',
                    'alias' => 'yii2-user-extended',
                    'catid' => '1',
                    'userid' => '1',
                    'introtext' => '<p><strong>Yii2 User Extended</strong> permette di estendere le potenzialità di <strong>Yii2 User</strong> by Dektrium, aggiungendo nuovi campi, un\'immagine utente, ecc...</p>',
                    'fulltext' => '',
                    'state' => '1',
                    'access' => 'public',
                    'language' => 'all',
                    'theme' => 'blog',
                    'ordering' => '7',
                    'hits' => '0',
                    'image' => '',
                    'image_caption' => '',
                    'image_credits' => '',
                    'video' => '',
                    'video_type' => 'youtube',
                    'video_caption' => '',
                    'video_credits' => '',
                    'created' => '2016-04-23 03:46:00',
                    'created_by' => '9900',
                    'modified' => '2016-04-23 04:14:35',
                    'modified_by' => '9900',
                    'params' => '',
                    'metadesc' => '',
                    'metakey' => '',
                    'robots' => 'index, follow',
                    'author' => 'Gogodigital S.r.l.s.',
                    'copyright' => 'Gogodigital S.r.l.s.',
                ],[
                    'id' => '8',
                    'title' => 'Yii2 Menù',
                    'alias' => 'yii2-men',
                    'catid' => '1',
                    'userid' => '1',
                    'introtext' => '<p><strong>Yii2 Menu</strong> è una estensione che permette di gestire un menù in maniera dinamica all\'interno di un sito Yii 2 con una <strong>interfaccia di amministrazione ed un widget</strong></p>',
                    'fulltext' => '<p><strong>Yii2 Menu</strong> è una estensione che permette di gestire un menù in maniera dinamica all\'interno di un sito Yii 2 con una semplice <strong>interfaccia di amministrazione ed un widget</strong>.</p>',
                    'state' => '1',
                    'access' => 'public',
                    'language' => 'all',
                    'theme' => 'blog',
                    'ordering' => '8',
                    'hits' => '0',
                    'image' => '',
                    'image_caption' => '',
                    'image_credits' => '',
                    'video' => '',
                    'video_type' => 'youtube',
                    'video_caption' => '',
                    'video_credits' => '',
                    'created' => '2016-04-27 10:32:14',
                    'created_by' => '9900',
                    'modified' => '2016-04-27 15:24:29',
                    'modified_by' => '9900',
                    'params' => '',
                    'metadesc' => '',
                    'metakey' => '',
                    'robots' => 'index, follow',
                    'author' => 'Gogodigital S.r.l.s.',
                    'copyright' => 'Gogodigital S.r.l.s.',
                ]
            ]
        );
    }

    public function down()
    {
        $this->dropTable('{{%article_items}}');
    }
}
